#!/usr/bin/env ansible-playbook
- name: Configure Errbit to store RefineryCMS logs
  hosts: errbit, refinerycms
  sudo: yes
  gather_facts: True

  tasks:
    - name: restart machine
      shell: sleep 2 && reboot
      async: 1
      poll: 0
      sudo: yes
      ignore_errors: true

    - name: wait for server to come back
      local_action: wait_for host={{ inventory_hostname }}  state=started delay=3 timeout=30
      sudo: no

    - name: Add errbit to hosts files
      shell: echo "192.168.56.10 errbit" >> /etc/hosts
      sudo: yes

    - name: Add refinreycms to hosts files
      shell: echo "192.168.56.11 refinerycms" >> /etc/hosts
      sudo: yes

    - copy: src=config/add-errbit-app.sh dest=/home/vagrant/errbit/add-errbit-app.sh mode=0755
      when: inventory_hostname in 'errbit'

    - name: Add revinerycms app to Errbit Mongo database
      command: /home/vagrant/errbit/add-errbit-app.sh    
      when: inventory_hostname in 'errbit'

    - copy: src=config/errbit.rb dest=/home/vagrant/my_new_application/config/initializers/errbit.rb owner=vagrant group=vagrant mode=0755
      when: inventory_hostname in 'refinerycms'

    - name: Start Errbit
      command: /home/vagrant/errbit/errbit-start.sh
      when: inventory_hostname in 'errbit'

    - name: Start RefineryCMS
      command: /home/vagrant/my_new_application/refinerycms-start.sh
      when: inventory_hostname in 'refinerycms'

