#!/usr/bin/env ansible-playbook
- name: Downloading and deploying Errbit
  hosts: errbit 
  sudo: yes
  gather_facts: True
  vars: 
   errbithome: /home/vagrant/errbit
   githuburl: 'https://github.com/errbit/errbit'
   mongohost: localhost
   mongoport: 27017
   mongopass: Q1w2e3r4t5y6
   mongouser: mongoadmin
  tasks:
    - name: clone errbit repository
      git: repo={{ githuburl }} dest={{ errbithome }}

    - name: Bundler thing
      command: /usr/bin/gem2.1 install bundler

    - name: Bundle install 
      command: /usr/local/bin/bundle install
      args: 
       chdir: '{{ errbithome }}'
      register: bundleout      

    - debug: msg="{{ bundleout.stdout }}"
    
    - name: Bundle exec
      command: /usr/local/bin/bundle exec rake errbit:bootstrap
      args:
          chdir: '{{ errbithome }}'
      environment: 
          MONGO_URL: "mongodb://{{ mongouser }}:{{ mongopass }}@{{ mongohost  }}:{{ mongoport }}/admin"
      register: dbing
  
    - debug: msg="{{ dbing.stdout }}"

    - copy: src=config/start.sh dest=/home/vagrant/errbit/start.sh
    - file: path=/home/vagrant/errbit/start.sh mode=0755
    - file: path=/etc/nginx/sites-enabled/default state=absent
    - copy: src=config/nginx.conf dest=/etc/nginx/sites-enabled/rails.conf
    - service: name=nginx state=restarted 
