#!/usr/bin/env ansible-playbook
- name: Downloading and deploying Refinerycms 
  hosts: refinerycms 
  sudo: yes
  gather_facts: True
  vars: 
   refineryhome: /home/vagrant/refinerycms
   githuburl: 'https://github.com/refinery/refinerycms'
  tasks:
    - file: path={{ refineryhome }} state=directory owner=vagrant group=vagrant mode=0755

    - name: Add RVM key
      shell: "curl -sSL https://rvm.io/mpapis.asc | gpg2 --import - "

    - name: Install RVM
      shell: "curl -sSL https://get.rvm.io | bash"

    - name: Ser RVM Env
      shell: . /etc/profile

    - name: Install ruby2.1.2
      command: /usr/local/rvm/bin/rvm install 2.1.2

    - name: Set to ruby2.1.2
      shell: echo "rvm 2.1.2" >> /etc/bashrc
      args:
        executable: /bin/bash
      sudo: yes

    - name: Bundler
      command: gem install bundler
      environment:
        PATH: "/usr/local/rvm/gems/ruby-2.1.2/bin:/usr/local/rvm/gems/ruby-2.1.2@global/bin:/usr/local/rvm/rubies/ruby-2.1.2/bin:$PATH"
        GEM_HOME: "/usr/local/rvm/gems/ruby-2.1.2"
        GEM_PATH: "/usr/local/rvm/gems/ruby-2.1.2:/usr/local/rvm/gems/ruby-2.1.2@global"
        MY_RUBY_HOME: "/usr/local/rvm/rubies/ruby-2.1.2"
        IRBRC: "/usr/local/rvm/rubies/ruby-2.1.2/.irbrc"
      register: dbug
      sudo: yes

    - debug: msg={{ dbug.stdout }}

    - name: clone refinerycms repository
      git: repo={{ githuburl }} dest={{ refineryhome }}

    - name: Bundler update psych
      command: /usr/local/rvm/rubies/ruby-2.1.2/bin/gem update psych

    - name: Bundler install execjs gem
      command: /usr/local/rvm/rubies/ruby-2.1.2/bin/gem install execjs

    - name: Bundler install therubyrace gem
      command: /usr/local/rvm/rubies/ruby-2.1.2/bin/gem install therubyracer

    - name: Add airbreak to Gemfile
      shell: echo "gem 'airbrake', '~> 5.0'" >> /home/vagrant/refinerycms/Gemfile
      sudo: yes

    - name: Bundle install
      command: /usr/local/rvm/gems/ruby-2.1.2/bin/bundle install
      args:
        chdir: '{{ refineryhome }}'
      environment:
        GEM_HOME: "/usr/local/rvm/gems/ruby-2.1.2"
        GEM_PATH: "/usr/local/rvm/gems/ruby-2.1.2:/usr/local/rvm/gems/ruby-2.1.2@global"
        MY_RUBY_HOME: "/usr/local/rvm/rubies/ruby-2.1.2"
        IRBRC: "/usr/local/rvm/rubies/ruby-2.1.2/.irbrc"
        PATH: "/usr/local/rvm/gems/ruby-2.1.2/bin:/usr/local/rvm/gems/ruby-2.1.2@global/bin:/usr/local/rvm/rubies/ruby-2.1.2/bin:/usr/local/rvm/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home/vagrant/.local/bin:/home/vagrant/bin"
      register: bundleout
      sudo: yes

    - debug: msg={{ bundleout.stdout }}

    - name: Install RefineryCMS Application
      command: /usr/local/rvm/gems/ruby-2.1.2/bin/rails new my_new_application -m http://refinerycms.com/t/edge
      environment:
        GEM_HOME: "/usr/local/rvm/gems/ruby-2.1.2"
        GEM_PATH: "/usr/local/rvm/gems/ruby-2.1.2:/usr/local/rvm/gems/ruby-2.1.2@global"
        MY_RUBY_HOME: "/usr/local/rvm/rubies/ruby-2.1.2"
        IRBRC: "/usr/local/rvm/rubies/ruby-2.1.2/.irbrc"
        PATH: "/usr/local/rvm/gems/ruby-2.1.2/bin:/usr/local/rvm/gems/ruby-2.1.2@global/bin:/usr/local/rvm/rubies/ruby-2.1.2/bin:/usr/local/rvm/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home/vagrant/.local/bin:/home/vagrant/bin"

    - file: path=/home/vagrant/my_new_application state=directory owner=vagrant group=vagrant recurse=yes

    - name: Stop firewall
      command: systemctl stop firewalld
      sudo: yes

    - name: Disable firewall
      command: systemctl disable firewalld
      sudo: yes

    - copy: src=config/refinerycms-start.sh dest=/home/vagrant/my_new_application/refinerycms-start.sh
    - file: path=/home/vagrant/refinerycms/refinerycms-start.sh mode=0755
