#!/usr/bin/env ansible-playbook
- name: Restart Errbit and RefineryCMSi machines
  hosts: errbit, refinerycms
  sudo: yes
  gather_facts: True

  tasks:
    - name: restart machine
      shell: sleep 2 && reboot
      async: 1
      poll: 0
      sudo: yes
      ignore_errors: true


